// <auto-generated />
using BlazorTestApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorTestApp.Migrations.TodoDb
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240313115822_TODO")]
    partial class TODO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorTestApp.Models.Cpr", b =>
                {
                    b.Property<int>("CprId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CprId"));

                    b.Property<string>("CprNr")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CprId");

                    b.ToTable("Cprs");
                });

            modelBuilder.Entity("BlazorTestApp.Models.TodoList", b =>
                {
                    b.Property<int>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToDoListId"));

                    b.Property<int>("CprId")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("ToDoListId");

                    b.HasIndex("CprId");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("BlazorTestApp.Models.TodoList", b =>
                {
                    b.HasOne("BlazorTestApp.Models.Cpr", "Cpr")
                        .WithMany("TodoList")
                        .HasForeignKey("CprId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpr");
                });

            modelBuilder.Entity("BlazorTestApp.Models.Cpr", b =>
                {
                    b.Navigation("TodoList");
                });
#pragma warning restore 612, 618
        }
    }
}
